# Generated by Django 5.2 on 2025-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseparticipant',
            name='share_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenseparticipant',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
